function [enorm, ecomp, tsec] = one_run_score_err( ...
    y,T,N,M,B, ...
    in_dist,in_pars,trans,tr_pars,g,g_pars, ...
    seed0, ...
    cpf_choice,traj_mode,trans_logpdf, ...
    store_parts,store_anc,store_logw, ...
    N_init,init_mode, g_anal)

t0 = tic;
out_pg = pgibbs_run_init_pfmean( ...
    y, T, N, M, B, ...
    in_dist, in_pars, ...
    trans, tr_pars, ...
    g, g_pars, ...
    seed0, ...
    cpf_choice, ...
    traj_mode, trans_logpdf, ...
    store_parts, store_anc, store_logw, ...
    N_init, init_mode);
tsec = toc(t0);

X_paths = out_pg.X_paths;                  % 1×T×M×(B+1)
S_mc    = score_gaussian_from_paths_vectorized(y, X_paths, tr_pars.theta, tr_pars.q, g_pars.R, in_pars.Sigma, true);
g_mc    = [S_mc.avg_obs; S_mc.avg_trans; S_mc.avg_init];  % [dr; dtheta; dq; dS0]
diff    = g_mc - g_anal;
enorm   = norm(diff,2);
ecomp   = abs(diff).';
end

%%
% Observation gradient (wrt r): returns p_obs×T×P with p_obs=1
