function out = pgibbs_run_init_pfmean( ...
    y, T, N, M, B, ...
    in_dist_samp, in_pars, ...
    trans_dist_samp, trans_pars, ...
    g, g_pars, ...
    seed0, ...
    cpf_choice, ...
    traj_mode, trans_logpdf, ...
    store_particles, store_ancestors, store_logw, ...
    N_init, init_mode)

% Defaults
if nargin < 13 || isempty(cpf_choice),   cpf_choice   = "cpf_parallel"; end
if nargin < 14 || isempty(traj_mode),    traj_mode    = "ancestors";    end
if nargin < 15, trans_logpdf = []; end
if nargin < 16 || isempty(store_particles), store_particles = false; end
if nargin < 17 || isempty(store_ancestors), store_ancestors = false; end
if nargin < 18 || isempty(store_logw),      store_logw      = false; end
if nargin < 19 || isempty(N_init),          N_init          = N;     end
if nargin < 20 || isempty(init_mode),       init_mode       = "weighted"; end

cpf_choice = lower(string(cpf_choice));
traj_mode  = lower(string(traj_mode));
init_mode  = lower(string(init_mode));

if ~(cpf_choice=="cpf" || cpf_choice=="cpf_parallel")
    error('cpf_choice must be "cpf" or "cpf_parallel".');
end
if traj_mode=="backward" && ~isa(trans_logpdf,'function_handle')
    error('traj_mode="backward" requires trans_logpdf.');
end
if size(y,2) ~= T, error('size(y,2)=%d ≠ T=%d', size(y,2), T); end

% Probe d_x
X0 = in_dist_samp(in_pars, max(1,N), max(1,M));
d_x = size(X0,1);

% ---- 1) Build M independent initial paths from PF(s) ----
x_init_paths = pf_weighted_mean_paths( ...
    y, T, N_init, M, ...
    in_dist_samp, in_pars, ...
    trans_dist_samp, trans_pars, ...
    g, g_pars, seed0, init_mode);       % d_x×T×M

% ---- 2) PG over B links, store B+1 paths ----
X_paths = zeros(d_x, T, M, B+1, 'like', x_init_paths);
X_paths(:,:,:,1) = x_init_paths;

cpf_fun = str2func(char(cpf_choice));
time_per_iter = zeros(1, B);

x_ref = x_init_paths;
for b = 1:B
    t0 = tic;
    out_cpf = cpf_fun(y, T, N, M, ...
                      in_dist_samp, in_pars, ...
                      trans_dist_samp, trans_pars, ...
                      g, g_pars, ...
                      x_ref, seed0 + (b-1), ...
                      traj_mode, trans_logpdf, ...
                      store_particles, store_ancestors, store_logw);
    time_per_iter(b) = toc(t0);

    X_paths(:,:,:,b+1) = out_cpf.sampled_path;
    x_ref = out_cpf.sampled_path;   % condition next step on current sample
end

% ---- 3) package ----
out.X_paths       = X_paths;           % d_x×T×M×(B+1)
out.time_per_iter = time_per_iter;
out.init_from     = sprintf('PF %s mean (N_init=%d, M=%d)', char(init_mode), N_init, M);
out.settings = struct('T',T,'N',N,'M',M,'B',B, ...
                      'cpf_choice',char(cpf_choice), ...
                      'traj_mode',char(traj_mode), ...
                      'seed0',seed0, ...
                      'N_init',N_init, 'init_mode',char(init_mode), ...
                      'store_particles',store_particles, ...
                      'store_ancestors',store_ancestors, ...
                      'store_logw',store_logw);
end


% ===== helper: run a PF and return the weighted filtered mean path (d_x×T) =====
